

// Create the function "aBCheck(string)" that accepts a string parameter.
// Return the STRING value "true" if the characters a or b are
// separated by 3 places anywhere in the string at least one time. 
//Otherwise return the STRING value "false"
 
// EXAMPLES:
// INPUT: aBCheck("pane borrowed");
// OUTPUT: "true"
// INPUT: aBCheck("chainsbreak")
// OUTPUT: "true"
// INPUT: aBCheck("painsarc");
// OUTPUT: "true"

function aBCheck(string){
	if("a" || "b" )

		return true;

	else{
		return false;
	}
}

aBCheck("barbecue");

//we have to make a function that says if a || b are separated by 3 places, then 
// it's true

